"""The PNGs in web/ have to arrive already squeezed.

Chromium's encoder is fast rather than tight, so a PNG straight out of the
generator is 13-45% bigger than the same pixels need to be. The generator runs
optipng for that reason; this holds the bytes to it, so a PNG that skipped the
step — regenerated by an older script, or drawn by hand and copied in — can't
ship. Recompressing is lossless, so there is nothing to trade off.
"""

import os
import shutil
import subprocess
from pathlib import Path

import pytest

WEB = Path(__file__).parent.parent / "web"
PNGS = sorted(WEB.rglob("*.png"))

# A different optipng version may find a little more than ours did, so this
# can't demand zero. It only has to be well under raw-Chromium bloat.
SLACK = 0.05


def require_optipng() -> None:
    """Absent locally is a skip; absent in CI is the bug this test guards.

    Skipping there would leave the suite green while nothing checks the assets
    at all, which is the one outcome worse than not having the test.
    """
    if shutil.which("optipng") is not None:
        return
    if os.environ.get("CI"):
        pytest.fail("optipng missing in CI — the workflow is meant to install it")
    pytest.skip("optipng not installed")


@pytest.mark.parametrize("png", PNGS, ids=lambda p: p.name)
def test_png_is_already_optimized(png: Path, tmp_path: Path) -> None:
    require_optipng()
    copy = tmp_path / png.name
    shutil.copy(png, copy)
    # -o2, not the generator's -o7: it finds all the same bloat (raw Chromium
    # output loses 13% at worst) for a tenth of the time, and this runs often.
    subprocess.run(["optipng", "-quiet", "-o2", "-strip", "all", copy], check=True)
    committed, squeezed = png.stat().st_size, copy.stat().st_size
    assert squeezed >= committed * (1 - SLACK), (
        f"{png.name} recompresses from {committed} to {squeezed} bytes — "
        "run scripts/generate_assets.py, or optipng it in place"
    )


def test_there_are_pngs_to_check() -> None:
    """So the parametrized test above can't pass by finding nothing."""
    assert PNGS
